# Generated by Django 6.0.6 on 2026-07-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('genre', models.CharField(max_length=100, verbose_name='Gênero')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
            ],
            options={
                'verbose_name': 'Filme',
                'verbose_name_plural': 'Filmes',
                'db_table': 'movies',
                'ordering': ['-created_at'],
            },
        ),
    ]
